### ISSUE TITLE
/add Does Not Support Passphrase

### ISSUE THREAD

**Issue by bambams** [raeesbhatti/ssh-agent-helper#1]
I'm not sure if it will be possible to do so securely, but it would be ideal if we could prompt the user for their passphrase and pass that along to ssh-add. As it is, the user sees the ssh-add prompt, but the program doesn't wait for input. It appears to just exit. Perhaps ssh-add detects that it's not connected to the console. I'm not sure. I haven't looked further into it. You can still use ssh-agent-helper with a passphrase, but can't use the /add switch. You just have to invoke ssh-add yourself after (i.e., register startup with no arguments if desired).

**Comment by RaeesBhatti** [comment]
It could be done that there is a prompt for the pass phrase each time you login (assuming that the key you're adding requires pass phrase) but it is unexpectedly tricky to get working. I've been trying to implement since about four hours now. While I will most likely get it done eventually, I personally don't think it's a good idea.

I'm exploring Windows Credential Manager APIs to see if they can provide a better solution to this.

**Comment by bambams** [comment]
I don't think it's something you'd want to do during "start up". It _might_ be possible to do for /add from the command prompt. But I agree, it will probably be trick to do, let alone to do **_securely_**. I understand if you don't want to spend too much time on it. I've tried to finagle .NET Process interface before and it's no fun...

**Comment by RaeesBhatti** [comment]
I've added a not-so good support for passphrases in the program, which will allow you one chance to enter the passphrase for your protected key. But I really recommend that you use `ssh-add` for it. If you have registered `ssh-agent-helper` at startup time, it will set the environment and you'll be able to use `ssh-add` in CMD or PowerShell. Or if you don't want it to setup the environment at login, you can run the `ssh-agent-helper` manually with no switches from CMD and copy and execute the two `set` commands in its output. That will allow you to start using `ssh-add` immediately in that console. Similarly for other already started consoles, you'll have to either exit and start them again or execute the same commands in them.

**Comment by bambams** [comment]
This looks like a sensible first try. I applaud you for getting that far. I know the Process class is not entirely intuitive (at least to me). I haven't had the chance to test this, but I trust that it works. My only concern would be whether or not the memory involved that contains the passphrase is "secure", and whether it's securely passed on to the subprocess (i.e., particularly no way for a different user of the system to access it).

In the event that we're not certain it might be wise to prompt the user with a warning first. I'm not sure if this code is going to prevent the passphrase from being echoed, but if not it certainly should warn the user (and probably should be possible to fix that at least).

The user always has the option of using ssh-add directly, which is probably more likely to be scrutinized by many more experienced eyes. I wouldn't want a bug in this software to go unaddressed and leave people vulnerable without giving them some warning that it hasn't been thoroughly "audited" until enough eyes with enough experience have been able to confirm that what it's doing is secure.

What do you think? Should we add a warning? Thanks for taking the time to work out a solution so quickly.

**Comment by RaeesBhatti** [comment]
It actually intercepts the key press events which prevents them from being printed in the console, but the characters are stored as String in memory, which is less secure than a SecureString. I'm working on a fix to use SecureString instead, thank you for the suggestion.

Forgive me for my inexperience, this is my first ever C# project. I was going to write this in GoLang but then I decided to learn C# 😄

**Comment by RaeesBhatti** [comment]
As for the delivery of the password to the `ssh-agent` process, it has to be done in String format because Windows does not provide SecureString API at the OS level. So, I guess we'll just show a warning for that.

**Comment by RaeesBhatti** [comment]
Unexpectedly, the solution was very simply to bind the console to parent process. I looked for this solution for hours yesterday. Nonetheless, it is working perfectly and as secure as `ssh-add` because the `ssh-agent-helper` just hands the console `ssh-add` until it is exists, so the process itself never deals with the passphrase.

**Comment by RaeesBhatti** [comment]
I've created a new release, so, you can try that out.

**Comment by bambams** [comment]
Strange, it seems something must be getting corrupted in the process because ssh-add refuses my passphrase through ssh-agent-helper, but works directly... I'll try to debug and report back.

**Comment by bambams** [comment]
By the way, you're doing a good job with C#. I'm impressed with how simply you're manipulating Process. Microsoft's API falls far short of intuition...
