### ISSUE TITLE
Usage / Switch Parsing Appears Inconsistent

### ISSUE THREAD

**Issue by bambams** [raeesbhatti/ssh-agent-helper#2]
The program appears to require /startup in addition to /add for the agent to be started prior to running ssh-add, but the usage does not make this clear. I suggest refactoring the program into two steps: first loop over the arguments, one-by-one, parsing switches and storing the state of what the user wants to do in variables (e.g., add=true, keys=new List<string>{ "C:\blah\id_rsa.pub" }, register_startup=true, unregister_startup=false, etc.).

Once arguments have been processed and what to do is stored conveniently then we can do it a single time instead of repeating calls (e.g., to addKeys()). Hopefully that will make processing the arguments more clear and will simplify the program.

The usage could also be updated if necessary to ensure it's clear and correct.

**Comment by RaeesBhatti** [comment]
A very good idea indeed. Will work on it, thank you.

**Comment by RaeesBhatti** [comment]
The switches have been changed from Windows style (`/switch`) to UNIX style (`--switch`), so, you'll have to redo the startup registration.
