### ISSUE TITLE
Health Check / Duplicate Process

### ISSUE THREAD

**Issue by bambams** [raeesbhatti/ssh-agent-helper#3]
I wonder if ssh-agent-helper should be checking for an existing process via the environment, and starting a new one if it cannot find one. For example, ssh-agent normally puts its PID into the SSH_AGENT_PID variable. It might be possible to check for the existence of that process and start a new one, overwriting the variables if it doesn't exist. It might be possible to ALWAYS do this. Similarly, before starting a new process, it would be ideal to check for an existing one running and skip starting a new one if one is already running (and the environment is already setup for it). Giving the user the ability to kill extraneous processes might also be useful (e.g., ssh-agent is already running, but it's PID doesn't match the environment; would you like to try to kill it?). Just thoughts...

**Comment by RaeesBhatti** [comment]
I was actually working on that right now 😄
